// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: micro/examples/blog/comment/proto/comment/comment.proto

package go_micro_service_comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Comment service

func NewCommentEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Comment service

type CommentService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Comment_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Comment_PingPongService, error)
}

type commentService struct {
	c    client.Client
	name string
}

func NewCommentService(name string, c client.Client) CommentService {
	return &commentService{
		c:    c,
		name: name,
	}
}

func (c *commentService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Comment.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Comment_StreamService, error) {
	req := c.c.NewRequest(c.name, "Comment.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &commentServiceStream{stream}, nil
}

type Comment_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type commentServiceStream struct {
	stream client.Stream
}

func (x *commentServiceStream) Close() error {
	return x.stream.Close()
}

func (x *commentServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *commentServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *commentServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *commentServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commentService) PingPong(ctx context.Context, opts ...client.CallOption) (Comment_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Comment.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &commentServicePingPong{stream}, nil
}

type Comment_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type commentServicePingPong struct {
	stream client.Stream
}

func (x *commentServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *commentServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *commentServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *commentServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *commentServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *commentServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Comment service

type CommentHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Comment_StreamStream) error
	PingPong(context.Context, Comment_PingPongStream) error
}

func RegisterCommentHandler(s server.Server, hdlr CommentHandler, opts ...server.HandlerOption) error {
	type comment interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Comment struct {
		comment
	}
	h := &commentHandler{hdlr}
	return s.Handle(s.NewHandler(&Comment{h}, opts...))
}

type commentHandler struct {
	CommentHandler
}

func (h *commentHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CommentHandler.Call(ctx, in, out)
}

func (h *commentHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CommentHandler.Stream(ctx, m, &commentStreamStream{stream})
}

type Comment_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type commentStreamStream struct {
	stream server.Stream
}

func (x *commentStreamStream) Close() error {
	return x.stream.Close()
}

func (x *commentStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *commentStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *commentStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *commentStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *commentHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CommentHandler.PingPong(ctx, &commentPingPongStream{stream})
}

type Comment_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type commentPingPongStream struct {
	stream server.Stream
}

func (x *commentPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *commentPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *commentPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *commentPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *commentPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *commentPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
